### ISSUE TITLE
AMODE privileges are undocumented

### ISSUE THREAD

**Issue by Mikaela** [ergochat/ergo#1958]
https://github.com/ergochat/ergo/pull/1902/files says +v overrides +i and +h overrides +b, but is this actually mentioned anywhere? Do +o, +a and +q also have secret privileges?

* [x] Update documentation that amode +v overrides +i (#1959)
* [x] Mention in documentation that amode +h overrides +b (#1959)
* [x] Are there others? At least we ran out of restricting characters? (#1959)
